Document: everybeam
Title: Debian everybeam Manual
Author: <insert document author here>
Abstract: This manual describes what everybeam is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/everybeam/everybeam.sgml.gz

Format: postscript
Files: /usr/share/doc/everybeam/everybeam.ps.gz

Format: text
Files: /usr/share/doc/everybeam/everybeam.text.gz

Format: HTML
Index: /usr/share/doc/everybeam/html/index.html
Files: /usr/share/doc/everybeam/html/*.html
